### PR TITLE
Animated stickers support added

### PR DESCRIPTION
**Pull request by Swapkumbhar31**
Animated stickers support added

### CODE REVIEW

**Comment by whopiyush** [comment]
uwu, waiting for this

**Comment by chuiizeet** [comment]
Nice! Maybe tomorrow try animated stickers

**Comment by whopiyush** [comment]
> 
> 
> Nice! Maybe tomorrow try animated stickers

How was it? Does it work?

**Comment by Swapkumbhar31** [comment]
> > Nice! Maybe tomorrow try animated stickers
> 
> How was it? Does it work?

It worked nicely for my project. If any changes are needed, then let me know.

**Comment by whopiyush** [comment]
> 
> 
> > > Nice! Maybe tomorrow try animated stickers
> > 
> > 
> > How was it? Does it work?
> 
> It worked nicely for my project. If any changes are needed, then let me know.

Oh I see, I think merging this would take quite a bit, what do you think of publishing your version temporarily on pub?

**Comment by vincekruger** [comment]
Apologies everyone. Have been super busy with other projects.

**Comment by vincekruger** [comment]
I'll pull this down today and push a new release to pub.

**Comment by whopiyush** [comment]
Thanks @Swapkumbhar31 @vincekruger <3

**Comment by chuiizeet** [comment]
> > > Nice! Maybe tomorrow try animated stickers
> 
> > 
> 
> > How was it? Does it work?
> 
> 
> 
> It worked nicely for my project. If any changes are needed, then let me know.

Works like a charm. My app is already up on the store 😀

**Comment by davidsss6** [comment]
There are any special configuration to use?
I try to add one animated sticker using the default project, replacing one of the default images with other of my animateds images, but the error: "pack is not marked as animated pack but contains animated stickers." keeps appearing. 

 Whatsapp testing version is 2.21.16.20
I using the ^1.0.1+5 version of flutter_whatsapp_stickers

Sorry for any missing information or error. This is my first message here in Github

Thanks  😀 😀

**Comment by whopiyush** [comment]
You need to have `animated_sticker_pack` set to `true` in your pack's config file.

More pack config options - https://github.com/WhatsApp/stickers/blob/master/Android/README.md#modifying-the-contentsjson-file

**Pull request merged**
